ver: 9
debug: false

#强制要求加载资源包(当拥有rpgarmour.nopack权限时无视)
forgeResourcePack: false
#吃东西时播放声音
EatSound:
  ROTTEN_FLESH: minecraft:moe.burp  #吃腐肉时播放moe.burp
  SWEET_BERRIES: minecraft:moe.huaq

#自定义物品配置
CustItemSetting:
  BambooDragonfly:  #竹蜻蜓
    flySpeed: 0.03
  SeekerBow:
    spawnChance: 0.080 #生成到怪物手上的几率
    itemDropChance: 0.25 #掉落几率

  EnderBow:  #末影弓
    spawnChance: 0.075
    itemDropChance: 0.25
    swapVehicle: true    #交换坐骑

  EnderHat:  #末影使者
    spawnChance: 0.075
    itemDropChance: 0.25

  SamuraiSword:  #武士刀
    spawnChance: 0.075
    itemDropChance: 0.25
    damage: 10    #伤害
    skillDamage: 18.5   #技能伤害

  ResurrectArmor: #妖精庇护r
    cooldown: 120    #被动CD
  Creeper:
    fuze: 50

#自定义实体配置
CustEntitySetting:
  SkeletonWin:  #骷髅王
    spawnChance: #生成几率
      _def_: 0.02 #缺省值所有世界生成几率
      world: 0.025 #world主世界生成几率
    itemDropChance: 0.25
    dropexp: 600 #掉落经验值

  ZombieWarrior:  #僵尸武士配置
    spawnChance:
      _def_: 0.025
      world: 0.03
    itemDropChance: 0.9
    dropexp: 600

  SlimeWin:  #骷髅王配置
    spawnChance:
      _def_: 0.025
      world: 0.03
    size: 10
