ver: 8
debug: false

#强制要求加载资源包(当拥有rpgarmour.nopack权限时无视)
forgeResourcePack: false
#吃东西时播放声音
EatSound:
  #吃腐肉时播放moe.burp
  ROTTEN_FLESH: minecraft:moe.burp
  SWEET_BERRIES: minecraft:moe.huaq

CustItemSetting:
  #竹蜻蜓
  BambooDragonfly:
    flySpeed: 0.03
  SeekerBow:
    #生成到怪物手上的几率
    spawnChance: 0.080
    #掉落几率
    itemDropChance: 0.25
  #末影弓
  EnderBow:
    spawnChance: 0.075
    itemDropChance: 0.25
    #交换坐骑
    swapVehicle: true
  QuickFiringCrossbow:
    spawnChance: 0.075
    itemDropChance: 0.25
  #末影使者
  EnderHat:
    spawnChance: 0.075
    itemDropChance: 0.25
  #武士刀
  SamuraiSword:
    spawnChance: 0.075
    itemDropChance: 0.25
    #伤害
    damage: 10
    #技能伤害
    skillDamage: 18.5
  ResurrectArmor:
    #被动CD
    cooldown: 120
  Creeper:
    fuze: 50

CustEntitySetting:
  #骷髅王
  SkeletonWin:
    #生成几率
    spawnChance:
      #缺省值所有世界生成几率
      _def_: 0.02
      #world主世界生成几率
      world: 0.025
    itemDropChance: 0.25
    dropexp: 600
  ZombWarrior:
    spawnChance:
      _def_: 0.025
      world: 0.03
    itemDropChance: 0.9
    dropexp: 600
  ZombWin:
    spawnChance:
      _def_: 0.01
    itemDropChance: 0.9
    dropexp: 600
  SlimeWin:
    spawnChance:
      _def_: 0.025
      world: 0.03
    size: 10
